In [4]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr
train = pd.read_csv('https://raw.githubusercontent.com/gibsonjackson/FODS-Assignment-2/main/Train.csv')
m=len(train)

In [5]:
y_train=train['Appliances'].tolist()

In [6]:
train=train.drop(columns = 'Appliances')

In [7]:
train = (train - train.mean())/train.std()

In [5]:
train.head()

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0 -0.558269 -0.908886 -1.053940 -0.471249 -0.340829 -1.251785 -0.529426   
1  0.187255 -0.069643  0.824607 -0.514343  0.046245 -0.280861  0.300104   
2 -1.537925  1.168722 -0.785577  0.593906 -1.423657  1.450227 -0.637766   
3  0.269407 -0.522315  0.735152 -0.967238  0.781196 -1.118782  0.731848   
4  0.057867  0.086826 -0.517213  0.900443  0.291228  0.151911 -0.238363   

       RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0 -1.147968 -0.442995  1.330007  ... -0.090325 -0.818386 -0.333029   
1 -0.093362  0.409024  0.364176  ...  0.627939  0.015921  0.631154   
2  1.040894 -1.023433  0.207574  ... -1.281992  0.650284 -0.264026   
3 -0.788008  0.574103 -0.680320  ...  0.627939 -0.288412 -0.002932   
4 -0.093362  0.201345 -0.461806  ...  0.339001  0.218275 -0.167048   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.862752 -0.089927  -0.490918   -0.876211  -0.370140 -0.389074 -0.389074  
1    -0.375544 -1.423832   1.543760    0.138755  -0.212277 -1.665812 -1.665812  
2     0.226501 -0.246857   0.797712    0.138755  -0.388989 -0.449091 -0.449091  
3     0.144404 -0.583136   0.526421    0.138755  -0.325373  1.134425  1.134425  
4    -0.548859  1.109468  -0.897853   -0.791631   0.513417 -1.277015 -1.277015  

[5 rows x 26 columns]

In [8]:
train_mat=train.to_numpy()

In [7]:
train_mat

array([[-0.55826896, -0.9088859 , -1.05394042, ..., -0.37013956,
        -0.38907353, -0.38907353],
       [ 0.18725531, -0.06964291,  0.82460655, ..., -0.21227745,
        -1.66581209, -1.66581209],
       [-1.53792483,  1.16872161, -0.78557657, ..., -0.38898876,
        -0.44909128, -0.44909128],
       ...,
       [ 0.31048246, -0.76413113,  0.87977023, ..., -0.03556614,
        -0.96494758, -0.96494758],
       [ 1.17307253, -2.6568207 ,  1.94278928, ..., -0.95446495,
         0.44179409,  0.44179409],
       [-1.66115198, -0.66623339, -1.05394042, ..., -1.61889947,
         1.18557858,  1.18557858]])

In [9]:
every_feature = np.transpose(train_mat)

In [9]:
every_feature

array([[-0.55826896,  0.18725531, -1.53792483, ...,  0.31048246,
         1.17307253, -1.66115198],
       [-0.9088859 , -0.06964291,  1.16872161, ..., -0.76413113,
        -2.6568207 , -0.66623339],
       [-1.05394042,  0.82460655, -0.78557657, ...,  0.87977023,
         1.94278928, -1.05394042],
       ...,
       [-0.37013956, -0.21227745, -0.38898876, ..., -0.03556614,
        -0.95446495, -1.61889947],
       [-0.38907353, -1.66581209, -0.44909128, ..., -0.96494758,
         0.44179409,  1.18557858],
       [-0.38907353, -1.66581209, -0.44909128, ..., -0.96494758,
         0.44179409,  1.18557858]])

In [10]:
all_corr_coeff=[]
for each_feature in every_feature:
  corr, _ = pearsonr(each_feature, y_train)
  all_corr_coeff.append(abs(corr))

In [11]:
all_corr_coeff

[0.04409235559554962,
 0.07248484553187452,
 0.10456257230051805,
 0.06737370475833353,
 0.07838129654155666,
 0.021820863315469625,
 0.02954126886985737,
 0.01145662443862904,
 0.009485938497272162,
 0.010789645202774048,
 0.11288138444759896,
 0.08155441210743328,
 0.014719541131410266,
 0.059713760833046886,
 0.03222861061433806,
 0.09119274903808137,
 0.0013263148276430312,
 0.056277878595495844,
 0.09695045075197088,
 0.03185845734056669,
 0.1564385191458652,
 0.08523746188182374,
 0.0034115026433806394,
 0.009386959843593314,
 0.002039324799156144,
 0.002039324799156144]

In [11]:
sorted_index = np.argsort(all_corr_coeff)[::-1]

In [13]:
sorted_index

array([20, 10,  2, 18, 15, 21, 11,  4,  1,  3, 13, 17,  0, 14, 19,  6,  5,
       12,  7,  9,  8, 23, 22, 24, 25, 16], dtype=int64)

In [15]:
def hypothesis(coeff,rowcount,feature_index):
  y_pred = 0.0
  for each_coeff,each_index in zip(coeff,feature_index):
    y_pred += each_coeff*every_feature[each_index][rowcount]
  return y_pred

In [16]:
def PCR(feature_index):
  coeff = np.zeros(len(feature_index))
  for i in range(1,10000):
    rowcount = 0
    for y_actual in y_train:
      y_pred = hypothesis(coeff,rowcount,feature_index)
      feature_matrix=np.zeros(len(feature_index))
      ind = 0
      for each_index in feature_index:
        feature_matrix[ind] = every_feature[each_index][rowcount]
        ind += 1
      coeff=coeff-0.001*(y_pred-y_actual)*feature_matrix
      rowcount += 1
  return coeff

In [17]:
all_coeff=[]
for i in range(0,26):
  coeff = PCR(sorted_index[0:i+1])
  all_coeff.append(coeff)
  print(all_coeff)
  print(i)

[array([-17.2722729])]
0
[array([-17.2722729]), array([-15.12566503,   5.44553529])]
1
[array([-17.2722729]), array([-15.12566503,   5.44553529]), array([-14.78951737,   3.58203839,   3.43955609])]
2
[array([-17.2722729]), array([-15.12566503,   5.44553529]), array([-14.78951737,   3.58203839,   3.43955609]), array([-15.31128383,  35.02667761,   4.10213897, -32.63423373])]
3
[array([-17.2722729]), array([-15.12566503,   5.44553529]), array([-14.78951737,   3.58203839,   3.43955609]), array([-15.31128383,  35.02667761,   4.10213897, -32.63423373]), array([-13.08285112,  33.56158334,   4.4042631 , -29.56644255,
         0.23550551])]
4
[array([-17.2722729]), array([-15.12566503,   5.44553529]), array([-14.78951737,   3.58203839,   3.43955609]), array([-15.31128383,  35.02667761,   4.10213897, -32.63423373]), array([-13.08285112,  33.56158334,   4.4042631 , -29.56644255,
         0.23550551]), array([ -8.55325884,  32.77322356,   6.83863443, -30.25087667,
        -3.54178133,   9.49830738

In [2]:
def cost(no_of_features,feature_index,coeff,curr_y):
  loss = 0.0
  rowcount = 0
  for y_pred in curr_y:
    feature_matrix=[0.0]*no_of_features
    index = 0
    for each in feature_index:
      feature_matrix[index]=every_feature[each][rowcount]
      index += 1
    rowcount += 1
    loss += (0.5/m)*(np.multiply(coeff,np.transpose(feature_matrix))-y_pred)**2
  sum_loss=0
  for each_loss in loss:
    sum_loss += each_loss
  avg_loss = sum_loss/m
  return avg_loss
  return loss

In [12]:
all_train_loss=[]
for i in range(0,26):
  loss = cost(i+1,sorted_index[0:i+1],all_coeff[i],y_train)
  all_train_loss.append(loss)

print(all_train_loss)

[1.6238555591452695, 3.261193039983767, 4.903523230134986, 6.721765852631606, 8.342465371305806, 9.980185207920087, 11.70129097558379, 13.791534534609946, 15.373193383518577, 17.52499815945703, 19.10468577318711, 20.75130243803931, 22.725908211463057, 24.384344919844914, 26.054486631969652, 27.623250091278646, 29.307424864638307, 31.00650295772734, 32.73805105712834, 34.41336231488225, 35.99039878487041, 37.64736845427274, 39.30401184522421, 40.938480356669885, 42.577752228359884, 44.181910558623244]


In [13]:
test = pd.read_csv('https://raw.githubusercontent.com/gibsonjackson/FODS-Assignment-2/main/Test%20(1).csv')
m=len(test)

In [23]:
test.head()

T1       RH_1         T2       RH_2         T3       RH_3  \
0  21.390000  35.626667  18.390000  38.090000  22.323333  35.790000   
1  22.323333  37.966667  21.890000  37.200000  21.200000  39.790000   
2  22.390000  32.200000  26.463333  25.600000  23.390000  33.790000   
3  24.600000  38.400000  24.000000  36.126667  26.200000  37.560000   
4  21.033333  36.060000  19.290000  36.693333  20.200000  35.163333   

          T4       RH_4     T5       RH_5  ...       RH_9  T_out  Press_mm_hg  \
0  20.500000  34.400000  19.70  47.730000  ...  39.466667   2.70   765.450000   
1  20.214198  40.825432  20.10  42.145000  ...  42.560000   2.03   756.466667   
2  22.890000  31.566667  20.73  38.560000  ...  37.590000  12.60   762.666667   
3  24.890000  35.950000  23.70  38.966667  ...  40.000000  18.40   751.450000   
4  20.200000  33.966667  17.79  44.966667  ...  38.930000   6.87   765.533333   

      RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  \
0  90.000000   1.000000   40.000000       1.15  30.928914  30.928914   
1  94.666667   7.000000   47.666667       1.23  41.385888  41.385888   
2  49.666667   4.333333   40.000000       2.23  45.831439  45.831439   
3  53.500000   3.000000   40.000000       8.55  25.329647  25.329647   
4  71.666667   2.000000   64.333333       2.00   0.395741   0.395741   

   Appliances  
0          60  
1          60  
2          70  
3          60  
4         120  

[5 rows x 27 columns]

In [14]:
y_test=test['Appliances'].tolist()
test=(test-test.mean())/test.std()
test=test.drop(columns = 'Appliances')
test_mat=test.to_numpy()
every_feature = np.transpose(test_mat)

In [15]:
all_test_loss=[]
for i in range(0,26):
  loss = cost(i+1,sorted_index[0:i+1],all_coeff[i],y_test)
  all_test_loss.append(loss)

print(all_test_loss)

[6.08967158905233, 12.23394242928662, 18.398466961760068, 25.26046134796334, 31.341620450537032, 37.476832383024956, 43.96168663152716, 51.92134754815893, 57.82078515122056, 66.04597365876275, 71.96013518089653, 78.15593710528461, 85.65221459634884, 91.88620950524688, 98.16374764996337, 104.05221002586211, 110.37588716942163, 116.80000573154761, 123.32812441180702, 129.62787564845024, 135.53287504168262, 141.76055149522526, 147.98653559043046, 154.12104755102598, 160.2736907378154, 166.27999764357287]
