In [1]:
import pandas as pd
import numpy as np
from tabulate import tabulate
from numpy.linalg import eig
train = pd.read_csv('https://raw.githubusercontent.com/gibsonjackson/FODS-Assignment-2/main/Train.csv')
m=len(train)

In [2]:
y_train=train['Appliances'].tolist()

In [3]:
train = (train - train.mean())/train.std()

In [4]:
train=train.drop(columns = 'Appliances')

In [5]:
train.head()

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0 -0.558269 -0.908886 -1.053940 -0.471249 -0.340829 -1.251785 -0.529426   
1  0.187255 -0.069643  0.824607 -0.514343  0.046245 -0.280861  0.300104   
2 -1.537925  1.168722 -0.785577  0.593906 -1.423657  1.450227 -0.637766   
3  0.269407 -0.522315  0.735152 -0.967238  0.781196 -1.118782  0.731848   
4  0.057867  0.086826 -0.517213  0.900443  0.291228  0.151911 -0.238363   

       RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0 -1.147968 -0.442995  1.330007  ... -0.090325 -0.818386 -0.333029   
1 -0.093362  0.409024  0.364176  ...  0.627939  0.015921  0.631154   
2  1.040894 -1.023433  0.207574  ... -1.281992  0.650284 -0.264026   
3 -0.788008  0.574103 -0.680320  ...  0.627939 -0.288412 -0.002932   
4 -0.093362  0.201345 -0.461806  ...  0.339001  0.218275 -0.167048   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.862752 -0.089927  -0.490918   -0.876211  -0.370140 -0.389074 -0.389074  
1    -0.375544 -1.423832   1.543760    0.138755  -0.212277 -1.665812 -1.665812  
2     0.226501 -0.246857   0.797712    0.138755  -0.388989 -0.449091 -0.449091  
3     0.144404 -0.583136   0.526421    0.138755  -0.325373  1.134425  1.134425  
4    -0.548859  1.109468  -0.897853   -0.791631   0.513417 -1.277015 -1.277015  

[5 rows x 26 columns]

In [6]:
train_mat=train.to_numpy()

In [7]:
train_mat

array([[-0.55826896, -0.9088859 , -1.05394042, ..., -0.37013956,
        -0.38907353, -0.38907353],
       [ 0.18725531, -0.06964291,  0.82460655, ..., -0.21227745,
        -1.66581209, -1.66581209],
       [-1.53792483,  1.16872161, -0.78557657, ..., -0.38898876,
        -0.44909128, -0.44909128],
       ...,
       [ 0.31048246, -0.76413113,  0.87977023, ..., -0.03556614,
        -0.96494758, -0.96494758],
       [ 1.17307253, -2.6568207 ,  1.94278928, ..., -0.95446495,
         0.44179409,  0.44179409],
       [-1.66115198, -0.66623339, -1.05394042, ..., -1.61889947,
         1.18557858,  1.18557858]])

In [8]:
every_feature = np.transpose(train_mat)

In [9]:
print(every_feature)

[[-0.55826896  0.18725531 -1.53792483 ...  0.31048246  1.17307253
  -1.66115198]
 [-0.9088859  -0.06964291  1.16872161 ... -0.76413113 -2.6568207
  -0.66623339]
 [-1.05394042  0.82460655 -0.78557657 ...  0.87977023  1.94278928
  -1.05394042]
 ...
 [-0.37013956 -0.21227745 -0.38898876 ... -0.03556614 -0.95446495
  -1.61889947]
 [-0.38907353 -1.66581209 -0.44909128 ... -0.96494758  0.44179409
   1.18557858]
 [-0.38907353 -1.66581209 -0.44909128 ... -0.96494758  0.44179409
   1.18557858]]


In [10]:
covariance_matrix=np.cov(train_mat,rowvar=False)

In [11]:
eigen_values = np.linalg.eigvals(covariance_matrix)


In [12]:
eigen_values

array([ 9.39893701e+00,  6.97920071e+00,  2.01064748e+00,  1.80158225e+00,
        1.07204524e+00,  9.32811588e-01,  9.69584986e-01,  5.64549461e-01,
        5.29824681e-01,  3.86244505e-01,  2.67723410e-01,  1.76177221e-01,
        1.47005453e-01,  1.38298930e-01,  1.20840939e-01,  1.13898224e-01,
        9.38272833e-02,  7.39727963e-02,  6.83146214e-02,  4.24929183e-02,
        4.45541612e-02,  3.61793680e-03,  1.39153206e-02,  2.80850911e-02,
        2.18477858e-02, -1.47196168e-17])

In [13]:
sorted_index = np.argsort(eigen_values)[::-1]
 
sorted_eigenvalue = eigen_values[sorted_index]

In [14]:
sorted_index

array([ 0,  1,  2,  3,  4,  6,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 20, 19, 23, 24, 22, 21, 25], dtype=int64)

In [15]:
#Calculating Variance
all_variance=[]
sum_variance=np.sum(eigen_values)
for i in range(0,26):
  sum = 0.0
  for j in range(0,i+1):
    sum += eigen_values[j]
  all_variance.append(sum/sum_variance)

print(all_variance)

[0.36149757742803557, 0.6299283738773506, 0.7072609691876944, 0.7765525941693155, 0.8177851033397683, 0.8536624721210178, 0.8909542023695238, 0.9126676431688777, 0.9330455154961809, 0.9479010733750947, 0.9581981276194488, 0.9649741745855102, 0.9706282304872554, 0.9759474200859621, 0.9805951484983381, 0.9849758494300604, 0.9885845910969795, 0.9914296986477589, 0.994057184084843, 0.9956915270960611, 0.9974051486820346, 0.9975443000974124, 0.9980795047346, 0.9991597005478702, 0.9999999999999998, 0.9999999999999998]


In [16]:
def hypothesis(coeff,rowcount,feature_index):
  y_pred = 0.0
  for each_coeff,each_index in zip(coeff,feature_index):
    y_pred += each_coeff*every_feature[each_index][rowcount]
  return y_pred

In [17]:
def PCR(feature_index):
  coeff = np.zeros(len(feature_index))
  for i in range(1,10000):
    rowcount = 0
    for y_actual in y_train:
      y_pred = hypothesis(coeff,rowcount,feature_index)
      feature_matrix=np.zeros(len(feature_index))
      ind = 0
      for each_index in feature_index:
        feature_matrix[ind] = every_feature[each_index][rowcount]
        ind += 1
      coeff=coeff-0.001*(y_pred-y_actual)*feature_matrix
      rowcount += 1
  return coeff

In [18]:
all_coeff=[]
for i in range(0,26):
  coeff = PCR(sorted_index[0:i+1])
  all_coeff.append(coeff)
  print(all_coeff)
  print(i)

print(tabulate(all_coeff))

[array([5.67182518])]
0
[array([5.67182518]), array([4.52215673, 9.78756401])]
1
[array([5.67182518]), array([4.52215673, 9.78756401]), array([-12.61759191,   7.32585401,  23.31451607])]
2
[array([5.67182518]), array([4.52215673, 9.78756401]), array([-12.61759191,   7.32585401,  23.31451607]), array([ 40.29508394,  83.20945748, -55.95962765, -80.36884564])]
3
[array([5.67182518]), array([4.52215673, 9.78756401]), array([-12.61759191,   7.32585401,  23.31451607]), array([ 40.29508394,  83.20945748, -55.95962765, -80.36884564]), array([ 15.80723997,  87.65365339, -62.82813389, -89.45397237,
        34.46835456])]
4
[array([5.67182518]), array([4.52215673, 9.78756401]), array([-12.61759191,   7.32585401,  23.31451607]), array([ 40.29508394,  83.20945748, -55.95962765, -80.36884564]), array([ 15.80723997,  87.65365339, -62.82813389, -89.45397237,
        34.46835456]), array([ 19.14114357,  85.36122669, -60.24024534, -88.03680597,
        37.89716043,  -9.1737447 ])]
5
[array([5.67182518])

In [23]:
def cost(no_of_features,feature_index,coeff,curr_y):
  loss = 0.0
  rowcount = 0
  for y_pred in curr_y:
    feature_matrix=[0.0]*no_of_features
    index = 0
    for each in feature_index:
      feature_matrix[index]=every_feature[each][rowcount]
      index += 1
    rowcount += 1
    loss += (0.5/m)*(np.multiply(coeff,np.transpose(feature_matrix))-y_pred)**2
  sum_loss=0
  for each_loss in loss:
    sum_loss += each_loss
  avg_loss = sum_loss/m
  return avg_loss
  return loss

In [24]:
all_train_loss=[]
for i in range(0,26):
  loss = cost(i+1,sorted_index[0:i+1],all_coeff[i],y_train)
  all_train_loss.append(loss)

print(all_train_loss)

[1.6435197204043732, 3.284359196322444, 4.955180844890742, 7.893717256022192, 9.740412559412066, 11.341998845960271, 12.984599654208608, 14.520744811215115, 16.11545306773726, 17.769004308064122, 19.562503711647416, 21.206880253558314, 22.84693685015146, 24.281190472858494, 25.92043665502864, 27.66249050687236, 29.133729074377822, 30.75958569875533, 32.658445039734595, 34.28958670356269, 35.92836115868384, 37.68940943051771, 39.32670517135121, 40.98480712763605, 42.54234315117104, 44.18191055881839]


In [36]:
test = pd.read_csv('https://raw.githubusercontent.com/gibsonjackson/FODS-Assignment-2/main/Test%20(1).csv')
m=len(test)

In [37]:
test.head()

T1       RH_1         T2       RH_2         T3       RH_3  \
0  21.390000  35.626667  18.390000  38.090000  22.323333  35.790000   
1  22.323333  37.966667  21.890000  37.200000  21.200000  39.790000   
2  22.390000  32.200000  26.463333  25.600000  23.390000  33.790000   
3  24.600000  38.400000  24.000000  36.126667  26.200000  37.560000   
4  21.033333  36.060000  19.290000  36.693333  20.200000  35.163333   

          T4       RH_4     T5       RH_5  ...       RH_9  T_out  Press_mm_hg  \
0  20.500000  34.400000  19.70  47.730000  ...  39.466667   2.70   765.450000   
1  20.214198  40.825432  20.10  42.145000  ...  42.560000   2.03   756.466667   
2  22.890000  31.566667  20.73  38.560000  ...  37.590000  12.60   762.666667   
3  24.890000  35.950000  23.70  38.966667  ...  40.000000  18.40   751.450000   
4  20.200000  33.966667  17.79  44.966667  ...  38.930000   6.87   765.533333   

      RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  \
0  90.000000   1.000000   40.000000       1.15  30.928914  30.928914   
1  94.666667   7.000000   47.666667       1.23  41.385888  41.385888   
2  49.666667   4.333333   40.000000       2.23  45.831439  45.831439   
3  53.500000   3.000000   40.000000       8.55  25.329647  25.329647   
4  71.666667   2.000000   64.333333       2.00   0.395741   0.395741   

   Appliances  
0          60  
1          60  
2          70  
3          60  
4         120  

[5 rows x 27 columns]

In [38]:
test=(test-test.mean())/(test.std())
y_test=test['Appliances'].tolist()
test=test.drop(columns = 'Appliances')
test_mat=test.to_numpy()
every_feature = np.transpose(test_mat)

In [39]:
all_test_loss=[]
for i in range(0,26):
  loss = cost(i+1,sorted_index[0:i+1],all_coeff[i],y_test)
  all_test_loss.append(loss)

print(all_test_loss)

[0.01028010641126373, 0.03668466559891863, 0.23861985486310922, 5.739738141337387, 6.667527980945866, 6.503868802632565, 6.503867202178686, 6.070882625657975, 5.889741896074284, 5.9315537999753545, 6.548055927732837, 6.549544241908441, 6.541318291714185, 5.803262843753747, 5.7901367890144595, 6.277980221363352, 5.623361296104219, 5.552630234726506, 6.583024683820324, 6.540274636983865, 6.515469874426843, 6.981031881839224, 6.948730117661136, 7.003645387998674, 6.661624157451054, 6.63755650522942]
